version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: usuario_db
    ports:
      - "5432:5432"
